-- Setup Tables for Campus Hunt Live Tracking

-- 1. Sessions Table
CREATE TABLE IF NOT EXISTS public.hunt_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nickname TEXT,
    start_time TIMESTAMPTZ DEFAULT now()
);

-- 2. Progress Table
CREATE TABLE IF NOT EXISTS public.hunt_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id UUID REFERENCES public.hunt_sessions(id) ON DELETE CASCADE,
    station_id INTEGER NOT NULL,
    status TEXT NOT NULL, -- 'correct' or 'task_completed'
    completed_at TIMESTAMPTZ DEFAULT now()
);

-- 3. Tasks Table (Metadata for videos)
CREATE TABLE IF NOT EXISTS public.hunt_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id UUID REFERENCES public.hunt_sessions(id) ON DELETE CASCADE,
    station_id INTEGER NOT NULL,
    video_url TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Enable Realtime for all tables
ALTER PUBLICATION supabase_realtime ADD TABLE hunt_sessions;
ALTER PUBLICATION supabase_realtime ADD TABLE hunt_progress;
ALTER PUBLICATION supabase_realtime ADD TABLE hunt_tasks;

-- Add RLS (Allow all for now for simplicity in a scavenger hunt)
ALTER TABLE hunt_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE hunt_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE hunt_tasks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow All sessions" ON hunt_sessions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All progress" ON hunt_progress FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All tasks" ON hunt_tasks FOR ALL USING (true) WITH CHECK (true);
